---
development:
  cloud_name: jessicamaycreative
  api_key: <%= Rails.application.secrets["api_key"] %>
  api_secret: <%= Rails.application.secrets["api_secret"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: jessicamaycreative
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: jessicamaycreative
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  enhance_image_tag: true
  static_image_support: false
