# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdfcf7bc15ed6f140c9b4527aa632bc47a7a824346f2fa7eacc6c3bce1ee7a31f119f66be84e3427e8529e604c9078959407538f6af1cbab54389ca8ddaccd25
  cloud_name: jessicamaycreative
  api_key: '211557442743395'
  api_secret: qybFSqeivC-_YPO_IF1EcBDkjFA

test:
  secret_key_base: d6c378b895f54706d936dce5b83c1315ab295a1036b574a48743a5218840f833d572a9946cf4e978c10a9c5159577baaa4aa36d8bba4168417d9ba5cd885178c
  cloud_name: jessicamaycreative
  api_key: '211557442743395'
  api_secret: qybFSqeivC-_YPO_IF1EcBDkjFA

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloud_name: jessicamaycreative
  api_key: '211557442743395'
  api_secret: qybFSqeivC-_YPO_IF1EcBDkjFA
